In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/137.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1"
}

In [4]:
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1' , headers = headers).text

In [5]:
soup = BeautifulSoup(webpage , 'lxml')

In [6]:
print(soup.prettify()[:1])

<

In [7]:
"".join(soup.find_all('h1')[0].text.split())

'TopCompaniesinINDIA'

In [92]:
cards = soup.find_all('div' , class_='companyCardWrapper__primaryInformation')

In [93]:
len(cards)

20

In [133]:
company_name = []
ratings = []
rating_count = []
highly_rated =[]
critical_rated = [] 
location = []
for i in cards :
    company_name.append(i.find('h2').text.strip())
    ratings.append(i.find('div' , class_='rating_star_container').text.strip())
    rating_count.append(i.find('span' , class_='companyCardWrapper__companyRatingCount').text.strip().strip("()"))
    location.append(i.find('span' , class_ = 'companyCardWrapper__interLinking').text.strip())
    
    try:
        high = i.find('span',class_='companyCardWrapper__ratingHeader--high'
        ).find_parent('div').find_next(
            'span',
            class_='companyCardWrapper__ratingValues'
        ).text.strip()
    except AttributeError:
        high = "NaN"

   
    try:
        critical = i.find('span',class_='companyCardWrapper__ratingHeader--critical'
        ).find_parent('div').find_next(
            'span',
            class_='companyCardWrapper__ratingValues'
        ).text.strip()
    except AttributeError:
        critical = "NaN"

    highly_rated.append(high)
    critical_rated.append(critical)

In [131]:
salaries = []
interviews = []
jobs = []
benefits = []

for i in card_wrapper:
    counts = i.find_all('span', class_='companyCardWrapper__ActionCount')

    salaries.append(counts[1].text.strip())
    interviews.append(counts[2].text.strip())
    jobs.append(counts[3].text.strip())
    benefits.append(counts[4].text.strip())

In [136]:
d = {'company_name' : company_name , 'ratings' : ratings , 'rating_count' : rating_count , 'highly_rated' : highly_rated , 
     'critical_rated' :critical_rated , 'location' : location, 'salaries' : salaries  , 'interviews': interviews , 'jobs' : jobs ,
    'benefits' : benefits}

{'company_name': ['TCS',
  'Accenture',
  'Wipro',
  'Cognizant',
  'Capgemini',
  'HDFC Bank',
  'Infosys',
  'HCLTech',
  'ICICI Bank',
  'Tech Mahindra',
  'Genpact',
  'TP',
  'Jio',
  'Axis Bank',
  'Concentrix Corporation',
  'Amazon',
  'Reliance Retail',
  'iEnergizer',
  'LTIMindtree',
  'HDB Financial Services'],
 'ratings': ['3.3',
  '3.7',
  '3.6',
  '3.7',
  '3.6',
  '3.8',
  '3.5',
  '3.4',
  '3.9',
  '3.3',
  '3.6',
  '3.9',
  '4.4',
  '3.6',
  '3.6',
  '3.9',
  '3.9',
  '4.6',
  '3.6',
  '3.9'],
 'rating_count': ['1.2L',
  '75k',
  '66.2k',
  '62.5k',
  '54.6k',
  '53.7k',
  '49.8k',
  '46.9k',
  '46.6k',
  '44.1k',
  '43.3k',
  '39.5k',
  '34k',
  '34k',
  '32.8k',
  '32.3k',
  '27.7k',
  '27.4k',
  '26.9k',
  '26.2k'],
 'highly_rated': ['Job Security',
  'NaN',
  'NaN',
  'NaN',
  'Work Life Balance, Job Security',
  'Job Security, Skill Development',
  'Job Security',
  'NaN',
  'Job Security, Promotions, Skill Development',
  'NaN',
  'Job Security',
  'Work Life Balance, Job Security, Skill Development',
  'Job Security, Skill Development, Company Culture',
  'NaN',
  'Job Security',
  'Company Culture, Work Life Balance, Salary',
  'Job Security, Skill Development, Work Life Balance',
  'Company Culture, Work Life Balance, Work Satisfaction',
  'NaN',
  'NaN'],
 'critical_rated': ['Promotions, Salary, Work Satisfaction',
  'Promotions, Salary, Work Satisfaction',
  'Promotions, Salary, Work Satisfaction',
  'Promotions, Salary, Work Satisfaction',
  'Promotions, Salary, Work Satisfaction',
  'Promotions, Salary',
  'Promotions, Salary, Work Satisfaction',
  'Promotions, Salary, Work Satisfaction',
  'NaN',
  'Promotions, Salary, Work Satisfaction',
  'Promotions, Salary, Work Satisfaction',
  'NaN',
  'NaN',
  'Promotions, Work Satisfaction, Company Culture',
  'Promotions, Salary, Work Satisfaction',
  'Promotions',
  'Promotions',
  'NaN',
  'Promotions, Salary, Work Satisfaction',
  'Promotions, Salary'],
 'location': ['IT Services & Consulting | Bengaluru +448 other locations',
  'IT Services & Consulting | Bengaluru +261 other locations',
  'IT Services & Consulting | Hyderabad +375 other locations',
  'IT Services & Consulting | Hyderabad +233 other locations',
  'IT Services & Consulting | Bengaluru +187 other locations',
  'Banking | Mumbai +1862 other locations',
  'IT Services & Consulting | Bengaluru +247 other locations',
  'IT Services & Consulting | Chennai +232 other locations',
  'Banking | Mumbai +1447 other locations',
  'IT Services & Consulting | Hyderabad +323 other locations',
  'Analytics & KPO | Hyderabad +181 other locations',
  'BPO | Mumbai +259 other locations',
  'Telecom | Mumbai +1965 other locations',
  'Banking | Mumbai +1532 other locations',
  'BPO | Bengaluru +185 other locations',
  'Internet | Bengaluru +521 other locations',
  'Retail | Mumbai +1167 other locations',
  'BPO | Noida +55 other locations',
  'IT Services & Consulting | Bengaluru +145 other locations',
  'NBFC | Mumbai +1098 other locations'],
 'salaries': ['10.3L',
  '7.1L',
  '4.9L',
  '6.1L',
  '4.9L',
  '1.5L',
  '5.3L',
  '3.9L',
  '1.6L',
  '2.9L',
  '2.4L',
  '1L',
  '62.1k',
  '1L',
  '1.3L',
  '1.6L',
  '74.9k',
  '25k',
  '2L',
  '49.5k'],
 'interviews': ['11.4k',
  '9.5k',
  '6.9k',
  '6.5k',
  '5.6k',
  '3.1k',
  '8.5k',
  '4.6k',
  '3k',
  '4.7k',
  '4k',
  '2.3k',
  '4.5k',
  '2k',
  '2k',
  '6.1k',
  '2k',
  '1.6k',
  '3.5k',
  '1.1k'],
 'jobs': ['4.8k',
  '23.7k',
  '4.2k',
  '945',
  '2.1k',
  '263',
  '3.2k',
  '240',
  '11',
  '691',
  '618',
  '1.8k',
  '--',
  '224',
  '17',
  '83',
  '101',
  '74',
  '556',
  '4'],
 'benefits': ['11k',
  '6.9k',
  '4.9k',
  '5.6k',
  '3.8k',
  '3.5k',
  '4.9k',
  '3.9k',
  '3.8k',
  '3.5k',
  '3.7k',
  '2k',
  '2.6k',
  '2.3k',
  '3.2k',
  '3.5k',
  '1.9k',
  '642',
  '852',
  '1.5k']}

In [138]:
df = pd.DataFrame(d)
df

,company_name,ratings,rating_count,highly_rated,critical_rated,location,salaries,interviews,jobs,benefits
0,TCS,3.3,1.2L,Job Security,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Bengaluru +448 othe...,10.3L,11.4k,4.8k,11k
1,Accenture,3.7,75k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Bengaluru +261 othe...,7.1L,9.5k,23.7k,6.9k
2,Wipro,3.6,66.2k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Hyderabad +375 othe...,4.9L,6.9k,4.2k,4.9k
3,Cognizant,3.7,62.5k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Hyderabad +233 othe...,6.1L,6.5k,945,5.6k
4,Capgemini,3.6,54.6k,"Work Life Balance, Job Security","Promotions, Salary, Work Satisfaction",IT Services & Consulting | Bengaluru +187 othe...,4.9L,5.6k,2.1k,3.8k
5,HDFC Bank,3.8,53.7k,"Job Security, Skill Development","Promotions, Salary",Banking | Mumbai +1862 other locations,1.5L,3.1k,263,3.5k
6,Infosys,3.5,49.8k,Job Security,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Bengaluru +247 othe...,5.3L,8.5k,3.2k,4.9k
7,HCLTech,3.4,46.9k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Chennai +232 other ...,3.9L,4.6k,240,3.9k
8,ICICI Bank,3.9,46.6k,"Job Security, Promotions, Skill Development",NaN,Banking | Mumbai +1447 other locations,1.6L,3k,11,3.8k
9,Tech Mahindra,3.3,44.1k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Hyderabad +323 othe...,2.9L,4.7k,691,3.5k
10,Genpact,3.6,43.3k,Job Security,"Promotions, Salary, Work Satisfaction",Analytics & KPO | Hyderabad +181 other locations,2.4L,4k,618,3.7k
11,TP,3.9,39.5k,"Work Life Balance, Job Security, Skill Develop...",NaN,BPO | Mumbai +259 other locations,1L,2.3k,1.8k,2k
12,Jio,4.4,34k,"Job Security, Skill Development, Company Culture",NaN,Telecom | Mumbai +1965 other locations,62.1k,4.5k,--,2.6k
13,Axis Bank,3.6,34k,NaN,"Promotions, Work Satisfaction, Company Culture",Banking | Mumbai +1532 other locations,1L,2k,224,2.3k
14,Concentrix Corporation,3.6,32.8k,Job Security,"Promotions, Salary, Work Satisfaction",BPO | Bengaluru +185 other locations,1.3L,2k,17,3.2k
15,Amazon,3.9,32.3k,"Company Culture, Work Life Balance, Salary",Promotions,Internet | Bengaluru +521 other locations,1.6L,6.1k,83,3.5k
16,Reliance Retail,3.9,27.7k,"Job Security, Skill Development, Work Life Bal...",Promotions,Retail | Mumbai +1167 other locations,74.9k,2k,101,1.9k
17,iEnergizer,4.6,27.4k,"Company Culture, Work Life Balance, Work Satis...",NaN,BPO | Noida +55 other locations,25k,1.6k,74,642
18,LTIMindtree,3.6,26.9k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Bengaluru +145 othe...,2L,3.5k,556,852
19,HDB Financial Services,3.9,26.2k,NaN,"Promotions, Salary",NBFC | Mumbai +1098 other locations,49.5k,1.1k,4,1.5k

In [145]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

# Helper function
def get_text(tag):
    return tag.text.strip() if tag else "NaN"

final = pd.DataFrame()

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/137.0.0.0 Safari/537.36"
    )
}

for j in range(1, 500):

    print(f"Scraping Page {j}")

    url = f"https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={j}"

    response = requests.get(url, headers=headers)

    if response.status_code != 200:
        print(f"Failed Page {j}")
        continue

    soup = BeautifulSoup(response.text, "lxml")

    cards = soup.find_all("div", class_="companyCardWrapper__primaryInformation")

    company_name = []
    ratings = []
    rating_count = []
    highly_rated = []
    critical_rated = []
    location = []
    salaries = []
    interviews = []
    jobs = []
    benefits = []

    for i in cards:

        # Company Name
        company_name.append(get_text(i.find("h2")))

        # Rating
        ratings.append(get_text(i.find("div", class_="rating_star_container")))

        # Rating Count
        rating_count.append(
            get_text(
                i.find("span", class_="companyCardWrapper__companyRatingCount")
            ).strip("()")
        )

        # Location
        location.append(
            get_text(
                i.find("span", class_="companyCardWrapper__interLinking")
            )
        )

        # Highly Rated
        try:
            high = (
                i.find("span", class_="companyCardWrapper__ratingHeader--high")
                .find_parent("div")
                .find_next(
                    "span",
                    class_="companyCardWrapper__ratingValues"
                )
                .text.strip()
            )
        except:
            high = "NaN"

        highly_rated.append(high)

        # Critical Rated
        try:
            critical = (
                i.find("span", class_="companyCardWrapper__ratingHeader--critical")
                .find_parent("div")
                .find_next(
                    "span",
                    class_="companyCardWrapper__ratingValues"
                )
                .text.strip()
            )
        except:
            critical = "NaN"

        critical_rated.append(critical)

        # Salaries / Interviews / Jobs / Benefits
        counts = i.find_all(
            "span",
            class_="companyCardWrapper__ActionCount"
        )

        salaries.append(counts[1].text.strip() if len(counts) > 1 else "NaN")
        interviews.append(counts[2].text.strip() if len(counts) > 2 else "NaN")
        jobs.append(counts[3].text.strip() if len(counts) > 3 else "NaN")
        benefits.append(counts[4].text.strip() if len(counts) > 4 else "NaN")

    df = pd.DataFrame({
        "company_name": company_name,
        "ratings": ratings,
        "rating_count": rating_count,
        "highly_rated": highly_rated,
        "critical_rated": critical_rated,
        "location": location,
        "salaries": salaries,
        "interviews": interviews,
        "jobs": jobs,
        "benefits": benefits
    })

    final = pd.concat([final, df], ignore_index=True)

print(final)

# Save to CSV
final.to_csv("AmbitionBox_Companies.csv", index=False)

Scraping Page 1
Scraping Page 2
Scraping Page 3
Scraping Page 4
Scraping Page 5
Scraping Page 6
Scraping Page 7
Scraping Page 8
Scraping Page 9
Scraping Page 10
Scraping Page 11
Scraping Page 12
Scraping Page 13
Scraping Page 14
Scraping Page 15
Scraping Page 16
Scraping Page 17
Scraping Page 18
Scraping Page 19
Scraping Page 20
Scraping Page 21
Scraping Page 22
Scraping Page 23
Scraping Page 24
Scraping Page 25
Scraping Page 26
Scraping Page 27
Scraping Page 28
Scraping Page 29
Scraping Page 30
Scraping Page 31
Scraping Page 32
Scraping Page 33
Scraping Page 34
Scraping Page 35
Scraping Page 36
Scraping Page 37
Scraping Page 38
Scraping Page 39
Scraping Page 40
Scraping Page 41
Scraping Page 42
Scraping Page 43
Scraping Page 44
Scraping Page 45
Scraping Page 46
Scraping Page 47
Scraping Page 48
Scraping Page 49
Scraping Page 50
Scraping Page 51
Scraping Page 52
Scraping Page 53
Scraping Page 54
Scraping Page 55
Scraping Page 56
Scraping Page 57
Scraping Page 58
Scraping Page 59
Scraping Page 60
Scraping Page 61
Scraping Page 62
Scraping Page 63
Scraping Page 64
Scraping Page 65
Scraping Page 66
Scraping Page 67
Scraping Page 68
Scraping Page 69
Scraping Page 70
Scraping Page 71
Scraping Page 72
Scraping Page 73
Scraping Page 74
Scraping Page 75
Scraping Page 76
Scraping Page 77
Scraping Page 78
Scraping Page 79
Scraping Page 80
Scraping Page 81
Scraping Page 82
Scraping Page 83
Scraping Page 84
Scraping Page 85
Scraping Page 86
Scraping Page 87
Scraping Page 88
Scraping Page 89
Scraping Page 90
Scraping Page 91
Scraping Page 92
Scraping Page 93
Scraping Page 94
Scraping Page 95
Scraping Page 96
Scraping Page 97
Scraping Page 98
Scraping Page 99
Scraping Page 100
Scraping Page 101
Scraping Page 102
Scraping Page 103
Scraping Page 104
Scraping Page 105
Scraping Page 106
Scraping Page 107
Scraping Page 108
Scraping Page 109
Scraping Page 110
Scraping Page 111
Scraping Page 112
Scraping Page 113
Scraping Page 114
Scraping Page 115
Scraping Page 116
Scraping Page 117
Scraping Page 118
Scraping Page 119
Scraping Page 120
Scraping Page 121
Scraping Page 122
Scraping Page 123
Scraping Page 124
Scraping Page 125
Scraping Page 126
Scraping Page 127
Scraping Page 128
Scraping Page 129
Scraping Page 130
Scraping Page 131
Scraping Page 132
Scraping Page 133
Scraping Page 134
Scraping Page 135
Scraping Page 136
Scraping Page 137
Scraping Page 138
Scraping Page 139
Scraping Page 140
Scraping Page 141
Scraping Page 142
Scraping Page 143
Scraping Page 144
Scraping Page 145
Scraping Page 146
Scraping Page 147
Scraping Page 148
Scraping Page 149
Scraping Page 150
Scraping Page 151
Scraping Page 152
Scraping Page 153
Scraping Page 154
Scraping Page 155
Scraping Page 156
Scraping Page 157
Scraping Page 158
Scraping Page 159
Scraping Page 160
Scraping Page 161
Scraping Page 162
Scraping Page 163
Scraping Page 164
Scraping Page 165
Scraping Page 166
Scraping Page 167
Scraping Page 168
Scraping Page 169
Scraping Page 170
Scraping Page 171
Scraping Page 172
Scraping Page 173
Scraping Page 174
Scraping Page 175
Scraping Page 176
Scraping Page 177
Scraping Page 178
Scraping Page 179
Scraping Page 180
Scraping Page 181
Scraping Page 182
Scraping Page 183
Scraping Page 184
Scraping Page 185
Scraping Page 186
Scraping Page 187
Scraping Page 188
Scraping Page 189
Scraping Page 190
Scraping Page 191
Scraping Page 192
Scraping Page 193
Scraping Page 194
Scraping Page 195
Scraping Page 196
Scraping Page 197
Scraping Page 198
Scraping Page 199
Scraping Page 200
Scraping Page 201
Scraping Page 202
Scraping Page 203
Scraping Page 204
Scraping Page 205
Scraping Page 206
Scraping Page 207
Scraping Page 208
Scraping Page 209
Scraping Page 210
Scraping Page 211
Scraping Page 212
Scraping Page 213
Scraping Page 214
Scraping Page 215
Scraping Page 216
Scraping Page 217
Scraping Page 218
Scraping Page 219
Scraping Page 220
Scraping Page 221
Scraping Page 222
Scraping Page 223
Scraping Page 224
Scraping Page 225
Scraping Page 226
Scraping Page 227
Scraping Page 228
Scraping Page 229
Scraping Page 230
Scraping Page 231
Scraping Page 232
Scraping Page 233
Scraping Page 234
Scraping Page 235
Scraping Page 236
Scraping Page 237
Scraping Page 238
Scraping Page 239
Scraping Page 240
Scraping Page 241
Scraping Page 242
Scraping Page 243
Scraping Page 244
Scraping Page 245
Scraping Page 246
Scraping Page 247
Scraping Page 248
Scraping Page 249
Scraping Page 250
Scraping Page 251
Scraping Page 252
Scraping Page 253
Scraping Page 254
Scraping Page 255
Scraping Page 256
Scraping Page 257
Scraping Page 258
Scraping Page 259
Scraping Page 260
Scraping Page 261
Scraping Page 262
Scraping Page 263
Scraping Page 264
Scraping Page 265
Scraping Page 266
Scraping Page 267
Scraping Page 268
Scraping Page 269
Scraping Page 270
Scraping Page 271
Scraping Page 272
Scraping Page 273
Scraping Page 274
Scraping Page 275
Scraping Page 276
Scraping Page 277
Scraping Page 278
Scraping Page 279
Scraping Page 280
Scraping Page 281
Scraping Page 282
Scraping Page 283
Scraping Page 284
Scraping Page 285
Scraping Page 286
Scraping Page 287
Scraping Page 288
Scraping Page 289
Scraping Page 290
Scraping Page 291
Scraping Page 292
Scraping Page 293
Scraping Page 294
Scraping Page 295
Scraping Page 296
Scraping Page 297
Scraping Page 298
Scraping Page 299
Scraping Page 300
Scraping Page 301
Scraping Page 302
Scraping Page 303
Scraping Page 304
Scraping Page 305
Scraping Page 306
Scraping Page 307
Scraping Page 308
Scraping Page 309
Scraping Page 310
Scraping Page 311
Scraping Page 312
Scraping Page 313
Scraping Page 314
Scraping Page 315
Scraping Page 316
Scraping Page 317
Scraping Page 318
Scraping Page 319
Scraping Page 320
Scraping Page 321
Scraping Page 322
Scraping Page 323
Scraping Page 324
Scraping Page 325
Scraping Page 326
Scraping Page 327
Scraping Page 328
Scraping Page 329
Scraping Page 330
Scraping Page 331
Scraping Page 332
Scraping Page 333
Scraping Page 334
Scraping Page 335
Scraping Page 336
Scraping Page 337
Scraping Page 338
Scraping Page 339
Scraping Page 340
Scraping Page 341
Scraping Page 342
Scraping Page 343
Scraping Page 344
Scraping Page 345
Scraping Page 346
Scraping Page 347
Scraping Page 348
Scraping Page 349
Scraping Page 350
Scraping Page 351
Scraping Page 352
Scraping Page 353
Scraping Page 354
Scraping Page 355
Scraping Page 356
Scraping Page 357
Scraping Page 358
Scraping Page 359
Scraping Page 360
Scraping Page 361
Scraping Page 362
Scraping Page 363
Scraping Page 364
Scraping Page 365
Scraping Page 366
Scraping Page 367
Scraping Page 368
Scraping Page 369
Scraping Page 370
Scraping Page 371
Scraping Page 372
Scraping Page 373
Scraping Page 374
Scraping Page 375
Scraping Page 376
Scraping Page 377
Scraping Page 378
Scraping Page 379
Scraping Page 380
Scraping Page 381
Scraping Page 382
Scraping Page 383
Scraping Page 384
Scraping Page 385
Scraping Page 386
Scraping Page 387
Scraping Page 388
Scraping Page 389
Scraping Page 390
Scraping Page 391
Scraping Page 392
Scraping Page 393
Scraping Page 394
Scraping Page 395
Scraping Page 396
Scraping Page 397
Scraping Page 398
Scraping Page 399
Scraping Page 400
Scraping Page 401
Scraping Page 402
Scraping Page 403
Scraping Page 404
Scraping Page 405
Scraping Page 406
Scraping Page 407
Scraping Page 408
Scraping Page 409
Scraping Page 410
Scraping Page 411
Scraping Page 412
Scraping Page 413
Scraping Page 414
Scraping Page 415
Scraping Page 416
Scraping Page 417
Scraping Page 418
Scraping Page 419
Scraping Page 420
Scraping Page 421
Scraping Page 422
Scraping Page 423
Scraping Page 424
Scraping Page 425
Scraping Page 426
Scraping Page 427
Scraping Page 428
Scraping Page 429
Scraping Page 430
Scraping Page 431
Scraping Page 432
Scraping Page 433
Scraping Page 434
Scraping Page 435
Scraping Page 436
Scraping Page 437
Scraping Page 438
Scraping Page 439
Scraping Page 440
Scraping Page 441
Scraping Page 442
Scraping Page 443
Scraping Page 444
Scraping Page 445
Scraping Page 446
Scraping Page 447
Scraping Page 448
Scraping Page 449
Scraping Page 450
Scraping Page 451
Scraping Page 452
Scraping Page 453
Scraping Page 454
Scraping Page 455
Scraping Page 456
Scraping Page 457
Scraping Page 458
Scraping Page 459
Scraping Page 460
Scraping Page 461
Scraping Page 462
Scraping Page 463
Scraping Page 464
Scraping Page 465
Scraping Page 466
Scraping Page 467
Scraping Page 468
Scraping Page 469
Scraping Page 470
Scraping Page 471
Scraping Page 472
Scraping Page 473
Scraping Page 474
Scraping Page 475
Scraping Page 476
Scraping Page 477
Scraping Page 478
Scraping Page 479
Scraping Page 480
Scraping Page 481
Scraping Page 482
Scraping Page 483
Scraping Page 484
Scraping Page 485
Scraping Page 486
Scraping Page 487
Scraping Page 488
Scraping Page 489
Scraping Page 490
Scraping Page 491
Scraping Page 492
Scraping Page 493
Scraping Page 494
Scraping Page 495
Scraping Page 496
Scraping Page 497
Scraping Page 498
Scraping Page 499
            company_name ratings rating_count  \
0                    TCS     3.3         1.2L
1              Accenture     3.7          75k
2                  Wipro     3.6        66.2k
3              Cognizant     3.7        62.5k
4              Capgemini     3.6        54.6k
...                  ...     ...          ...
9975     S.K.B. Builders     4.1          113
9976      Quale Infotech     4.4          113
9977          Bop Realty     4.6          113
9978  Atulaya Healthcare     3.6          113
9979       Vedanta Power     4.0          113

                                           highly_rated  \
0                                          Job Security
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                       Work Life Balance, Job Security
...                                                 ...
9975  Work Life Balance, Skill Development, Work Sat...
9976  Skill Development, Company Culture, Work Satis...
9977  Company Culture, Work Life Balance, Work Satis...
9978                                                NaN
9979                    Work Life Balance, Job Security

                                 critical_rated  \
0         Promotions, Salary, Work Satisfaction
1         Promotions, Salary, Work Satisfaction
2         Promotions, Salary, Work Satisfaction
3         Promotions, Salary, Work Satisfaction
4         Promotions, Salary, Work Satisfaction
...                                         ...
9975                                        NaN
9976                                        NaN
9977                                        NaN
9978  Job Security, Promotions, Company Culture
9979                                 Promotions

                                               location salaries interviews  \
0     IT Services & Consulting | Bengaluru +448 othe...      NaN        NaN
1     IT Services & Consulting | Bengaluru +261 othe...      NaN        NaN
2     IT Services & Consulting | Hyderabad +375 othe...      NaN        NaN
3     IT Services & Consulting | Hyderabad +233 othe...      NaN        NaN
4     IT Services & Consulting | Bengaluru +187 othe...      NaN        NaN
...                                                 ...      ...        ...
9975  Engineering & Construction | New Delhi +17 oth...      NaN        NaN
9976  IT Services & Consulting | New Delhi +9 other ...      NaN        NaN
9977             Real Estate | Noida +8 other locations      NaN        NaN
9978        Healthcare | Chandigarh +15 other locations      NaN        NaN
9979               Power | Bathinda +29 other locations      NaN        NaN

     jobs benefits
0     NaN      NaN
1     NaN      NaN
2     NaN      NaN
3     NaN      NaN
4     NaN      NaN
...   ...      ...
9975  NaN      NaN
9976  NaN      NaN
9977  NaN      NaN
9978  NaN      NaN
9979  NaN      NaN

[9980 rows x 10 columns]

In [146]:
final

,company_name,ratings,rating_count,highly_rated,critical_rated,location,salaries,interviews,jobs,benefits
0,TCS,3.3,1.2L,Job Security,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Bengaluru +448 othe...,NaN,NaN,NaN,NaN
1,Accenture,3.7,75k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Bengaluru +261 othe...,NaN,NaN,NaN,NaN
2,Wipro,3.6,66.2k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Hyderabad +375 othe...,NaN,NaN,NaN,NaN
3,Cognizant,3.7,62.5k,NaN,"Promotions, Salary, Work Satisfaction",IT Services & Consulting | Hyderabad +233 othe...,NaN,NaN,NaN,NaN
4,Capgemini,3.6,54.6k,"Work Life Balance, Job Security","Promotions, Salary, Work Satisfaction",IT Services & Consulting | Bengaluru +187 othe...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
9975,S.K.B. Builders,4.1,113,"Work Life Balance, Skill Development, Work Sat...",NaN,Engineering & Construction | New Delhi +17 oth...,NaN,NaN,NaN,NaN
9976,Quale Infotech,4.4,113,"Skill Development, Company Culture, Work Satis...",NaN,IT Services & Consulting | New Delhi +9 other ...,NaN,NaN,NaN,NaN
9977,Bop Realty,4.6,113,"Company Culture, Work Life Balance, Work Satis...",NaN,Real Estate | Noida +8 other locations,NaN,NaN,NaN,NaN
9978,Atulaya Healthcare,3.6,113,NaN,"Job Security, Promotions, Company Culture",Healthcare | Chandigarh +15 other locations,NaN,NaN,NaN,NaN
9979,Vedanta Power,4.0,113,"Work Life Balance, Job Security",Promotions,Power | Bathinda +29 other locations,NaN,NaN,NaN,NaN

In [134]:
location

['IT Services & Consulting | Bengaluru +448 other locations',
 'IT Services & Consulting | Bengaluru +261 other locations',
 'IT Services & Consulting | Hyderabad +375 other locations',
 'IT Services & Consulting | Hyderabad +233 other locations',
 'IT Services & Consulting | Bengaluru +187 other locations',
 'Banking | Mumbai +1862 other locations',
 'IT Services & Consulting | Bengaluru +247 other locations',
 'IT Services & Consulting | Chennai +232 other locations',
 'Banking | Mumbai +1447 other locations',
 'IT Services & Consulting | Hyderabad +323 other locations',
 'Analytics & KPO | Hyderabad +181 other locations',
 'BPO | Mumbai +259 other locations',
 'Telecom | Mumbai +1965 other locations',
 'Banking | Mumbai +1532 other locations',
 'BPO | Bengaluru +185 other locations',
 'Internet | Bengaluru +521 other locations',
 'Retail | Mumbai +1167 other locations',
 'BPO | Noida +55 other locations',
 'IT Services & Consulting | Bengaluru +145 other locations',
 'NBFC | Mumbai +1098 other locations']

In [132]:
jobs

['4.8k',
 '23.7k',
 '4.2k',
 '945',
 '2.1k',
 '263',
 '3.2k',
 '240',
 '11',
 '691',
 '618',
 '1.8k',
 '--',
 '224',
 '17',
 '83',
 '101',
 '74',
 '556',
 '4']

In [127]:
benefits

['11k',
 '6.9k',
 '4.9k',
 '5.6k',
 '3.8k',
 '3.5k',
 '4.9k',
 '3.9k',
 '3.8k',
 '3.5k',
 '3.7k',
 '2k',
 '2.6k',
 '2.3k',
 '3.2k',
 '3.5k',
 '1.9k',
 '642',
 '852',
 '1.5k']

In [124]:
interviews

['11.4k',
 '9.5k',
 '6.9k',
 '6.5k',
 '5.6k',
 '3.1k',
 '8.5k',
 '4.6k',
 '3k',
 '4.7k',
 '4k',
 '2.3k',
 '4.5k',
 '2k',
 '2k',
 '6.1k',
 '2k',
 '1.6k',
 '3.5k',
 '1.1k']

In [125]:
salaries

['10.3L',
 '7.1L',
 '4.9L',
 '6.1L',
 '4.9L',
 '1.5L',
 '5.3L',
 '3.9L',
 '1.6L',
 '2.9L',
 '2.4L',
 '1L',
 '62.1k',
 '1L',
 '1.3L',
 '1.6L',
 '74.9k',
 '25k',
 '2L',
 '49.5k']

In [90]:
critical_rated

['Promotions, Salary, Work Satisfaction',
 'Promotions, Salary, Work Satisfaction',
 'Promotions, Salary, Work Satisfaction',
 'Promotions, Salary, Work Satisfaction',
 'Promotions, Salary, Work Satisfaction',
 'Promotions, Salary',
 'Promotions, Salary, Work Satisfaction',
 'Promotions, Salary, Work Satisfaction',
 'NaN',
 'Promotions, Salary, Work Satisfaction',
 'Promotions, Salary, Work Satisfaction',
 'NaN',
 'NaN',
 'Promotions, Work Satisfaction, Company Culture',
 'Promotions, Salary, Work Satisfaction',
 'Promotions',
 'Promotions',
 'NaN',
 'Promotions, Salary, Work Satisfaction',
 'Promotions, Salary']

In [91]:
highly_rated

['Job Security',
 'NaN',
 'NaN',
 'NaN',
 'Work Life Balance, Job Security',
 'Job Security, Skill Development',
 'Job Security',
 'NaN',
 'Job Security, Promotions, Skill Development',
 'NaN',
 'Job Security',
 'Work Life Balance, Job Security, Skill Development',
 'Job Security, Skill Development, Company Culture',
 'NaN',
 'Job Security',
 'Company Culture, Work Life Balance, Salary',
 'Job Security, Skill Development, Work Life Balance',
 'Company Culture, Work Life Balance, Work Satisfaction',
 'NaN',
 'NaN']

In [45]:
rating_count

['1.2L',
 '75k',
 '66.2k',
 '62.5k',
 '54.6k',
 '53.7k',
 '49.8k',
 '46.9k',
 '46.6k',
 '44.1k',
 '43.3k',
 '39.5k',
 '34k',
 '34k',
 '32.8k',
 '32.3k',
 '27.7k',
 '27.4k',
 '26.9k',
 '26.2k']

In [31]:
ratings

['3.3',
 '3.7',
 '3.6',
 '3.7',
 '3.6',
 '3.8',
 '3.5',
 '3.4',
 '3.9',
 '3.3',
 '3.6',
 '3.9',
 '4.4',
 '3.6',
 '3.6',
 '3.9',
 '3.9',
 '4.6',
 '3.6',
 '3.9']

In [32]:
company_name

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'HCLTech',
 'ICICI Bank',
 'Tech Mahindra',
 'Genpact',
 'TP',
 'Jio',
 'Axis Bank',
 'Concentrix Corporation',
 'Amazon',
 'Reliance Retail',
 'iEnergizer',
 'LTIMindtree',
 'HDB Financial Services']

In [88]:
print(card.find("div", class_="companyCardWrapper__ratingComparisonWrapper").prettify())

<div class="companyCardWrapper__ratingComparisonWrapper">
 <!-- -->
 <div>
  <div class="companyCardWrapper__ratingHeader">
   <img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/>
   <span class="companyCardWrapper__ratingHeader--critical">
    Critically Rated For
   </span>
  </div>
  <span class="companyCardWrapper__ratingValues">
   Promotions, Salary
  </span>
 </div>
</div>